### ISSUE TITLE
Security issues - phpCAS library update

### ISSUE THREAD

**Issue by gaudreaj** [patrickpollet/mahara_plugin_auth_cas#5]
Hi Patrick,

I was about to integrate your CAS plugin into my installation of Mahara but then I saw that the phpCAS library is an old one (1.1.3) not supported anymore and with many security issues (See https://wiki.jasig.org/display/casc/phpcas).

I don't know if you still support this plugin, but if you do, it would be very important to update the library.

Best regards.

Jean-Philippe

**Comment by patrickpollet** [comment]
Done . Thanks to you ;-)
